name: Build and Publish Pre-Release NuGet Package on develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.*

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prepare SNK
      env: 
        NUGET_SIGNING_KEY: ${{ secrets.NUGET_SIGNING_KEY }}    
      run: echo "$NUGET_SIGNING_KEY" | base64 -d > RateLimiter/key.snk

    - name: Build
      run: dotnet build RateLimiter --configuration Release

    - name: Test
      run: dotnet test RateLimiterTests

    - name: Publish NuGet Package
      run: dotnet pack RateLimiter --version-suffix rc.$(date -u +%Y%m%d%H%M%S) --configuration Release --output ./artifacts
      
      # Add --version-suffix $(date -u +%Y%m%d%H%M%S) to generate a unique version
   
    # - name: Push NuGet package
    #   run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json